services:
  frontend-resume:
    container_name: nextjs
    build: ./frontend-resume
  proxy:
    container_name: "resume-proxy"
    build: ./nginx
    restart: always
    ports:
      - "80:80"
  backend-resume:
    build: ./backend-resume
    container_name: spring-server
    depends_on:
      - db
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=secret
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/my_database
      - SPRING_DATASOURCE_USERNAME=my_user
      - SPRING_DATASOURCE_PASSWORD=secret
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"

  db:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=my_user
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=my_database
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
    external: false
