services:
  frontend-resume:
    container_name: frontend-resume
    build: ./frontend-resume
  proxy:
    container_name: "resume-proxy"
    build: ./nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - frontend-resume
  backend-resume:
    build: ./backend-resume
    container_name: spring-server
    depends_on:
      db:
        condition: service_healthy
    environment:
      - POSTGRES_USER=my_user
      - POSTGRES_PASSWORD=secret
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/my_database
      - SPRING_DATASOURCE_USERNAME=my_user
      - SPRING_DATASOURCE_PASSWORD=secret
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  db:
    image: postgres:16
    container_name: postgres
    environment:
      - POSTGRES_USER=my_user
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=my_database
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U my_user -d my_database"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
    external: false
