services:
  frontend-resume:
    container_name: frontend-resume
    build: ./frontend-resume
  proxy:
    container_name: "resume-proxy"
    build: ./nginx
    restart: always
    ports:
      - "80:80"
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'
  backend-resume:
    container_name: backend-resume
    build: ./backend-resume
    depends_on:
      - postgres